name: file_picker_writable
description: |
  Flutter plugin to allow users to open files/documents which can be read, and written back at a
  later time as well as creating new files on external media.
version: 2.1.0+1
homepage: https://github.com/hpoul/file_picker_writable

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  convert: ^3.1.2
  synchronized: ^3.3.0+3
  path_provider: ^2.1.5
  path: ^1.9.0
  quiver: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: codeux.design.filepicker.file_picker_writable
        pluginClass: FilePickerWritablePlugin
      ios:
        pluginClass: FilePickerWritablePlugin
      macos:
        pluginClass: FilePickerWritablePlugin

